# Site settings
site: HB
title: MicroBlog - MicroBlogs
keywords: 鸿博, 微型博客
description: >-
  微型博客 - MicroBlogs
lang: zh-Hans
timezone:  China
repo: https://github.com/HelloPages/guestbook # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: HB
  bio: 边角料 <br> 打工人 <br> 躺平 /摆烂
  picture: assets/images/profile.png
  github: username # github username
  twitter: username # twitter username
  facebook: username # facebook username
  instagram: username # instagram username
  youtube: https://www.youtube.com/channel/UCMmAto-wxBootXN91AzBiDg # youtube username
  linkedin: username # linkedin username
  email: your-email@email.com # email adress


# URL settings
url: "https://hellopages.github.io/" # Domain Name of host. [username].github.io for github pages
# permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
